/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiWaitlistClaimRouteImport } from './routes/api/waitlist/claim'
import { Route as ApiWaitlistResendRouteImport } from './routes/api/waitlist/resend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistClaimRoute = ApiWaitlistClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ApiWaitlistRoute,
} as any)
const ApiWaitlistResendRoute = ApiWaitlistResendRouteImport.update({
  id: '/resend',
  path: '/resend',
  getParentRoute: () => ApiWaitlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/claim': typeof ApiWaitlistClaimRoute
  '/api/waitlist/resend': typeof ApiWaitlistResendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/claim': typeof ApiWaitlistClaimRoute
  '/api/waitlist/resend': typeof ApiWaitlistResendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/waitlist': typeof ApiWaitlistRouteWithChildren
  '/api/waitlist/claim': typeof ApiWaitlistClaimRoute
  '/api/waitlist/resend': typeof ApiWaitlistResendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/waitlist' | '/api/waitlist/claim' | '/api/waitlist/resend'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/waitlist' | '/api/waitlist/claim' | '/api/waitlist/resend'
  id:
    | '__root__'
    | '/'
    | '/api/waitlist'
    | '/api/waitlist/claim'
    | '/api/waitlist/resend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWaitlistRoute: typeof ApiWaitlistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist/claim': {
      id: '/api/waitlist/claim'
      path: '/claim'
      fullPath: '/api/waitlist/claim'
      preLoaderRoute: typeof ApiWaitlistClaimRouteImport
      parentRoute: typeof ApiWaitlistRoute
    }
    '/api/waitlist/resend': {
      id: '/api/waitlist/resend'
      path: '/resend'
      fullPath: '/api/waitlist/resend'
      preLoaderRoute: typeof ApiWaitlistResendRouteImport
      parentRoute: typeof ApiWaitlistRoute
    }
  }
}

interface ApiWaitlistRouteChildren {
  ApiWaitlistClaimRoute: typeof ApiWaitlistClaimRoute
  ApiWaitlistResendRoute: typeof ApiWaitlistResendRoute
}

const ApiWaitlistRouteChildren: ApiWaitlistRouteChildren = {
  ApiWaitlistClaimRoute: ApiWaitlistClaimRoute,
  ApiWaitlistResendRoute: ApiWaitlistResendRoute,
}

const ApiWaitlistRouteWithChildren = ApiWaitlistRoute._addFileChildren(
  ApiWaitlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWaitlistRoute: ApiWaitlistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
